name: REST API
on: [push]
jobs:
  REST-API-exists:
    runs-on: ubuntu-latest
    steps:
      - name: Test for existence
        run: /bin/false
      - name: Test for TLS 1.2
        run: /bin/false        
  REST-API-works:
    runs-on: ubuntu-latest
    steps:
      - name: Test for CRUD
        run: /bin/false
