name: REST API
on:
  push:
    branches:
      - test
      - main
jobs:
  REST-API-exists:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
