name: REST API
on: [push]
jobs:
  REST-API-exists:
    runs-on: ubuntu-latest
    steps:
      - name: Test that REST API exists
        run: /bin/false
      - name: Test that REST API serves TLS 1.2
        run: /bin/false        
