name: REST API
on: [push]
jobs:
  REST-API-exists:
    runs-on: ubuntu-latest
    steps:
      - name: Test that API exists
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2        
        run: |
          apis=$(aws apigateway get-rest-apis)
          found=$(echo $apis | jq '.items[] | select(.name=="hello_serverless")')
          if [[ $found == '' ]]; then
            echo $apis
            /bin/false
          fi
      - name: Test for TLS 1.2
        run: /bin/false        
  REST-API-works:
    runs-on: ubuntu-latest
    steps:
      - name: Test that health endpoint exists
        run: /bin/false
      - name: Test for optional CRUD
        run: /bin/false
