name: secrets
on: [push]
jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Test app can read them
        run: /bin/false
      - name: Flesh out good secret management
        run: /bin/false        

