name: Functional tests
on:
  push:
    branches:
      - rest-api
      - test
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-west-2
  TF_VAR_domain: ${{ secrets.domain }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Package app
        run: |
          cd hello.app
          python3 -mvenv venv
          . ./venv/bin/activate
          pip install --upgrade pip && pip install --upgrade setuptools
          [[ -e requirements.txt ]] && pip install -r requirements.txt
          [[ -e build-requirements.txt ]] && pip install -r build-requirements.txt
          make
      - name: Save zipfile for later
        uses: actions/upload-artifact@v2
        with:
          name: zipfile
          path: hello.app/hello.zip
      - name: Terraform
        run: |
          export TF_VAR_branch=${GITHUB_REF##*/}
          cd terraform
          terraform init
          terraform apply -auto-approve

  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Test HTTPS
        run: tests/functional/https.sh

  Cleanup:
    needs: [Build, Test]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Retrieve zipfile
        uses: actions/download-artifact@v2
        with:
          name: zipfile
          path: hello.app/hello.zip
      - name: Terraform
        run: |
          cd terraform
          terraform init
          terraform destroy -auto-approve
