name: Functional tests
on:
  push:
    branches:
      - rest-api
      - test
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Package app
        run: |
          cd hello.app
          python3 -mvenv venv
          . ./venv/bin/activate
          pip install --upgrade pip && pip install --upgrade setuptools
          [[ -e requirements.txt ]] && pip install -r requirements.txt
          [[ -e build-requirements.txt ]] && pip install -r build-requirements.txt
          make
      - name: Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
          TF_VAR_domain: ${{ secrets.domain }}
        run: |
          export TF_VAR_branch=${GITHUB_REF##*/}
          cd terraform
          terraform init
          terraform apply -auto-approve

  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
          TF_VAR_domain: ${{ secrets.domain }}
        run: |
          cd terraform
          terraform init
          URL=$(terraform output URL | sed -e 's/"//g')
          OUT=$(curl -s $URL)
          if [[ $OUT == '"Hello, serverless!"' ]] ; then
            /bin/true
          else
            /bin/false
          fi
  Cleanup:
    needs: [Build, Test]
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
          TF_VAR_domain: ${{ secrets.domain }}
        run: |
          cd terraform
          terraform destroy -auto-approve
