name: Unit tests
on: [push]
jobs:
  Pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Setup virtualenv
        run: |
          cd hello.app
          python3 -mvenv venv
          . ./venv/bin/activate
          pip install --upgrade pip && pip install --upgrade setuptools
          [[ -e requirements.txt ]] && pip install -r requirements.txt
          [[ -e build-requirements.txt ]] && pip install -r build-requirements.txt
          /bin/true # keep going even if build-requirements doesn't exist
      - name: Pytest
        run: cd hello.app && make test
